### ISSUE TITLE
19.1.603 breaks due to Reactive.Logger dependency

### ISSUE THREAD

**Issue by apobekiaris** [eXpandFramework/eXpand#571]
Thru Update from 602 to 603 I've  following issue after login, can this concern to the #542 
but its on standard Win App

Der Typ "DevExpress.Utils.Extensions.UtilsExtensions" in der Assembly "DevExpress.Utils.v19.1, Version=19.1.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" konnte nicht geladen werden.

   bei Xpand.XAF.Modules.Reactive.Logger.ModelReactiveModuleLogger.ReactiveLogger(IModelReactiveModules reactiveModules)
   bei Xpand.XAF.Modules.Reactive.Logger.ModelReactiveModuleLogger.<>c.<ReactiveLogger>b__0_0(IModelReactiveModules modules)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   bei System.Reactive.ExceptionHelpers.Throw(Exception exception)
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Do`1.Actions._.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   bei System.Reactive.ObserverBase`1.OnNext(T value)
   bei Xpand.XAF.Modules.Reactive.Extensions.TraceExtensions.<>c__DisplayClass6_1`1.<Trace>b__2(TSource v)
   bei System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei DevExpress.ExpressApp.XafApplication.OnLoggedOn(LogonEventArgs args)
   bei DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   bei DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)

_Originally posted by @rSeeFip in https://github.com/eXpandFramework/eXpand/issues/570#issuecomment-539516633_

**Comment by rSeeFip** [comment]
no, is still the same with Reactive Logger 0.0.8.2

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Remove CastTo method as not exists in 19.1.6 #571 #542](https://github.com/eXpandFramework/DevExpress.XAF/commit/cdfd3bb561f4adb92448ddc6004d65050e7e65e2)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
TypeLoadException is fixed for me in Reactive Logger 0.0.8.4

**Comment by krombipils** [comment]
I guess I'm wrong. Seems to be fixed if you reference only Reactive Logger. If eXpandSystem is referenced, updating only Reactive Logger to 0.0.8.4 does not fix the problem.  I think we have to wait for eXpand 19.1.603.2?!

**Comment by apobekiaris** [comment]
yes the bot will update u again once packages are bumped still working on it

**Comment by apobekiaris** [comment]
this was an update on the DevExpress.XAF repo

**Comment by apobekiaris** [comment]
however u should be able to test be installing the package explicitly as it has larger version it should lead, let me know if u try it

**Comment by krombipils** [comment]
My solution references 19.1.603.1 and I added an explicit reference to Reactive Logger 0.0.8.4, but the problem persists. I think I also have to update Xpand.XAF.Modules.GridListEditor and Xpand.XAF.Modules.RefreshView?

**Comment by apobekiaris** [comment]
rationally thinking u should be able to use the latest version somehow like a binding redirect? which version is loaded?

**Comment by krombipils** [comment]
![grafik](https://user-images.githubusercontent.com/8317504/66419229-fd7add80-ea03-11e9-8eeb-7de8df9f77fa.png)

This dlls/versions are loaded when the exception is thrown. Because there are also fixes e.g. in GridListEditor module, I think I have to manually update all problematic modules?

**Comment by apobekiaris** [comment]
thnks i ll have a look in your solution before pushing

**Comment by apobekiaris** [comment]
ah yes there are many modules that where fixed

**Comment by expand** [comment]
eXpand.lab release [19.1.603.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.603.2) includes commit that relate to this task:

* [Bump standalone packages #571 #542](https://github.com/eXpandFramework/eXpand.lab/commit/665ebb182c89428b0040a02429cc8929a55d726c)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
For me TypeLoadException is now really fixed in 19.1.603.2. Thank you!

**Comment by rSeeFip** [comment]
I've got Issue thrue 19.1.603.2 that XpandJobDetailDataMap is now privat and not public.
![image](https://user-images.githubusercontent.com/43534405/66451587-63478380-ea5d-11e9-8ae6-b060f315f4be.png)


It's not possible to inherits XpandJobDetailDataMap from Xpand.Persistent.BaseImpl.Jobscheduler

**Comment by rSeeFip** [comment]
Looks good. Thank you

**Comment by rSeeFip** [comment]
i've get now often an freeze by open an listview, or close an openview and activation of listview from background on step

ReactiveModule Information: 0 : XafApplicationRXExtensions.WhenListViewCreated(187): OnNext((SEE_4_U.Win.SEE_4_UWindowsFormsApplication, DevExpress.ExpressApp.ListViewCreatedEventArgs))

i got no issue ,nothing, just freezing of win app. In context with reactiveModule

**Comment by rSeeFip** [comment]
but logger client win i can install with nuget, because depency "akarnokd.reactive_extensions" can not resolved

**Comment by apobekiaris** [comment]
soory about it I am looking on it now #564

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Remove akarnokd.reactive_extensions #564 #571](https://github.com/eXpandFramework/DevExpress.XAF/commit/f07e3e40e1eb8f03338b228037ac20a399dc97fc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
604.1 is out and includes this update @isatahiri

**Comment by rSeeFip** [comment]
About freezing i found out that XPAnd.XAF.Modules.Reactive.Win is missing, by loading oneview

![image](https://user-images.githubusercontent.com/43534405/66546970-754d2300-eb3e-11e9-8238-b00261131597.png)

**Comment by apobekiaris** [comment]
nice! tell us also please how u discover it

**Comment by rSeeFip** [comment]
By coincident,   it's a guess because the file isn't in the package. Can I not test it

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [OneView: Incorrect Reactive.Win reference #571](https://github.com/eXpandFramework/DevExpress.XAF/commit/3352e3f775236dd54ea98c2ec6a6eff1c0c53988)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment]
Hello,

with 604.2 i got following message after logon, The process can destabilize the runtime.

![image](https://user-images.githubusercontent.com/43534405/66590810-e4079c00-eb91-11e9-8add-9cc85b5c24fc.png)

**Comment by rSeeFip** [comment]
out from logs:

Type:       VerificationException
	Message:    Dieser Vorgang kann die Laufzeit destabilisieren.
	Data:       0 entries
	Stack trace:

   bei CreateWindow_Patch1(XafApplication context, TemplateContext controllers, ICollection`1 createAllControllers, Boolean isMain, Boolean view, View )
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateExplorerWindow(ShowViewParameters parameters)
   bei DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowStartupWindowCore()
   bei DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowStartupWindowCore()
   bei DevExpress.ExpressApp.Win.WinApplication.ShowStartupWindow()
   bei DevExpress.ExpressApp.Win.WinApplication.DoStartupLogic(IOverlaySplashScreenHandle overlayFormHandle)
   bei DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
read this please
https://github.com/eXpandFramework/eXpand/issues/513#issuecomment-523386924

if u can provide a sample we can work on something

**Comment by rSeeFip** [comment]
i think it comes out from here

Unable to create an instance of the "ModelApplicationCreatorInfo" type.
Reason: "Die Methode "get_View" im Typ "ModelDevExpressXtraGridViewsGridCustomization_CustomizationForm" der Assembly "hz2j5sso, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung."

**Comment by apobekiaris** [comment]
look like the ModelMapper.dll gets corrupted try cleanup bin, obj folders??

**Comment by apobekiaris** [comment]
there is a long chat on Gitter that relates to ModelMapper that u may want to follow
https://gitter.im/xpandframework/community

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
